spring.application.name=config-service
server.port=9999
#spring.cloud.config.server.git.uri=https://github.com/Larsou/config-ecom-app
spring.cloud.config.server.git.uri=file:///Users/larbissou/Desktop/enset-projects/ecom-ii-bdcc-app/config-repo
